### ISSUE TITLE
Flash demo.bin with new bootloader

### ISSUE THREAD

**Issue by Dam5** [Dafang-Hacks/uboot#11]
Hello all, great projects.

A couple of weeks ago i bought a Xiaomi Dafang camera, for the sole reason to hack it and tinker with.
Flashed the cfw-1.3.bin (based on 5.5.1.243) + files as soon as I unboxed it. 

Mounted a serial header to follow bootprocess.

After some tinkering, flashed the new bootloader 'dafang_128mb_v2.bin'.

All went well, but I have problems with the stability of WiFi, even when in short distance of the AP.
A couple of times a day, randomly,  I get ping-responses (from another linux machine) of over 90 seconds.

I was looking for a newer firmware to try, but in one of the [project-issues](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/669#issuecomment-517898719) I found a suggestion to downgrade to 5.5.1.177.

So I copied the appropriate demo.bin to the SD-card and booted with SETUP-button pressed.
No update, normal boot followed.
Acccording to the serial log, and comparing this to previous log files, it seems this new bootloader doesn't check for the SETUP-button.
A short glance at the source code confirms this.

Now my question is:

Have I overlooked something, or is this deliberately?
I have read all the markdowns, but I can't remember a reference.

It's no problem to flash demo.bin some other way, but I was just wondering.

Cheers,
Rob

**Comment by Dam5** [comment]
Solved.

Modified the bootloader, so it included the check for SETUP-key.

Had also to apply [hansaya's #9](https://github.com/Dafang-Hacks/uboot/pull/9) patch  otherwise it wouldn't update to my (16MB) flash.

Rob

**Comment by Kaan88** [comment]
And where is this modification?
