### ISSUE TITLE
Neos Smartcam GD25Q128 128MB Chip?

### ISSUE THREAD

**Issue by jttri777** [Dafang-Hacks/uboot#16]
Good Evening,

Hardware: Neos Smartcam

After having logged an issue on the main Dafang Hacks Repository (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1475) attempting to get the v4l2rtspserver running I currently believe that an I have an issue with a library, and therefore could do with some extra space to add a few more for testing purposes.

On recommendation from nik0, in the previous issue, I have been looking into the older issues that have been raised on this repository and found https://github.com/Dafang-Hacks/uboot/issues/4 and https://github.com/Dafang-Hacks/uboot/issues/8.

Currently my camera detects a GD25Q128 chip on startup.

![image](https://user-images.githubusercontent.com/12187650/83667165-e5c11c80-a5c5-11ea-9c21-8bd3064f8cfd.png)

Etched onto the chip is the model number "25Q127CSIG". Datasheets online confirm that this is indeed an 128MB chip.

The line in the flash drivers header file: jz_sip.h states that my chip is recognised as a 16MB chip by the driver if I'm not mistaken?
https://github.com/Dafang-Hacks/uboot/blob/a1d19316522425d61035a9e897e9d8b0424b7f74/drivers/spi/jz_spi.h#L230

I will attempt to modify this and recompile and see if I can get it working on my camera.

Many Thanks,
James.

**Comment by fundef1** [comment]
uh... 128Mbit (not MByte) ?

**Comment by jttri777** [comment]
Yes, I am aren't I!!!.

According to the datasheet, the chip is an 128Mbit device = 16MBytes.

Thanks for clarifying that,
James.
